version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "CrateMgtBackend"
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
 
    volumes:
      - ./:/var/www/html
